name: Test workflow

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '2.10.2'
    - run: flutter pub get
    - name: Test
      run: flutter test --coverage --dart-define=CI=true
    - name: Exclude generated files from coverage
      run: dart pub run remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}